{% set name = "wraptile" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wraptile-{{ version }}.tar.gz
  sha256: df1148fb6d1fb0b9237728e3b70a33a5154442234a1c9f8c10c2cff08cc4de03

build:
  entry_points:
    - wraptile = wraptile.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fastapi
    - pydantic
    - pyyaml
    - typer
    - uvicorn
    - gavicore >=0.0.7
    - procodile >=0.0.7

test:
  imports:
    - wraptile
  commands:
    - pip check
    - wraptile --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/eo-tools/eozilla/tree/main/wraptile
  doc_url: https://eo-tools.github.io/eozilla/
  dev_url: https://github.com/eo-tools/eozilla/
  summary: A fast and light-weight server that implements the OGC API - Processes, Part 1.
  description: |
    Eozilla 🦖 Wraptile is a fast and light-weight server that implements the
    [OGC API - Processes, Part 1](https://github.com/opengeospatial/ogcapi-processes)
    for a given workflow orchestration system like Airflow.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - forman
    - pont-us
